import type { CategoryItem, HomepageData, HomepageSkill, TutorialItem } from "@/lib/types/homepage";

const categories: CategoryItem[] = [
  {
    id: "cat_writing",
    name: "写作",
    slug: "writing",
    icon: "pen",
    color: "blue",
    description: "文案写作、标题生成、内容润色等",
    skillCount: 2345,
  },
  {
    id: "cat_coding",
    name: "编程",
    slug: "coding",
    icon: "code",
    color: "green",
    description: "代码生成、调试、解释与优化",
    skillCount: 2128,
  },
  {
    id: "cat_office",
    name: "办公",
    slug: "office",
    icon: "briefcase",
    color: "orange",
    description: "文档处理、数据分析、PPT 等效率工具",
    skillCount: 2256,
  },
  {
    id: "cat_design",
    name: "设计",
    slug: "design",
    icon: "palette",
    color: "purple",
    description: "图像生成、UI 设计、创意视觉等",
    skillCount: 1789,
  },
  {
    id: "cat_marketing",
    name: "营销",
    slug: "marketing",
    icon: "megaphone",
    color: "rose",
    description: "社媒运营、广告文案、用户增长等",
    skillCount: 1654,
  },
  {
    id: "cat_learning",
    name: "学习",
    slug: "learning",
    icon: "graduation",
    color: "indigo",
    description: "知识问答、笔记总结、学习规划等",
    skillCount: 1402,
  },
  {
    id: "cat_video",
    name: "视频",
    slug: "video",
    icon: "video",
    color: "cyan",
    description: "脚本创作、分镜、剪辑辅助",
    skillCount: 1210,
  },
  {
    id: "cat_automation",
    name: "自动化",
    slug: "automation",
    icon: "bolt",
    color: "emerald",
    description: "工作流编排、Agent、任务串联",
    skillCount: 1098,
  },
];

const featuredSkills: HomepageSkill[] = [
  {
    id: "skill_xhs_title",
    title: "小红书爆款标题生成",
    slug: "xiaohongshu-title-generator",
    summary: "快速生成高点击率的小红书标题，提升曝光与互动率。",
    coverIcon: "document",
    categoryName: "写作",
    tags: [
      { id: "tag_xhs", name: "小红书", type: "scene" },
      { id: "tag_write", name: "写作", type: "type" },
      { id: "tag_easy", name: "简单", type: "difficulty" },
    ],
    difficulty: "beginner",
    favoriteCount: 8600,
    viewCount: 23000,
    isFeatured: true,
    isHot: true,
  },
  {
    id: "skill_meeting_notes",
    title: "会议纪要整理助手",
    slug: "meeting-notes-assistant",
    summary: "自动整理会议纪要和待办事项，提升协作效率。",
    coverIcon: "group",
    categoryName: "办公",
    tags: [
      { id: "tag_office", name: "办公", type: "scene" },
      { id: "tag_efficiency", name: "效率", type: "type" },
      { id: "tag_mid", name: "中等", type: "difficulty" },
    ],
    difficulty: "intermediate",
    favoriteCount: 6200,
    viewCount: 18400,
    isFeatured: true,
    isHot: false,
  },
  {
    id: "skill_resume_match",
    title: "简历优化与岗位匹配",
    slug: "resume-match-optimizer",
    summary: "优化简历内容并匹配岗位要求，提升面试命中率。",
    coverIcon: "resume",
    categoryName: "办公",
    tags: [
      { id: "tag_job", name: "求职", type: "scene" },
      { id: "tag_resume", name: "简历", type: "type" },
      { id: "tag_mid_2", name: "中等", type: "difficulty" },
    ],
    difficulty: "intermediate",
    favoriteCount: 5100,
    viewCount: 15100,
    isFeatured: true,
    isHot: false,
  },
];

const latestSkills: HomepageSkill[] = [
  {
    id: "skill_outline",
    title: "论文大纲生成器",
    slug: "paper-outline-generator",
    summary: "根据主题快速生成论文大纲与结构。",
    categoryName: "写作",
    tags: [
      { id: "tag_academic", name: "学术", type: "scene" },
      { id: "tag_write_2", name: "写作", type: "type" },
    ],
    difficulty: "beginner",
    favoriteCount: 2100,
    viewCount: 9200,
    isFeatured: false,
    isHot: false,
  },
  {
    id: "skill_excel",
    title: "Excel 数据分析助手",
    slug: "excel-data-helper",
    summary: "自动分析数据，生成图表与洞察。",
    categoryName: "办公",
    tags: [
      { id: "tag_excel", name: "Excel", type: "scene" },
      { id: "tag_data", name: "数据", type: "type" },
    ],
    difficulty: "beginner",
    favoriteCount: 1800,
    viewCount: 8400,
    isFeatured: false,
    isHot: false,
  },
  {
    id: "skill_prd",
    title: "产品需求文档生成",
    slug: "prd-generator",
    summary: "一键生成结构完整、清晰的 PRD。",
    categoryName: "办公",
    tags: [
      { id: "tag_product", name: "产品", type: "scene" },
      { id: "tag_doc", name: "文档", type: "type" },
    ],
    difficulty: "beginner",
    favoriteCount: 1600,
    viewCount: 7800,
    isFeatured: false,
    isHot: false,
  },
  {
    id: "skill_midjourney",
    title: "Midjourney 提示词优化",
    slug: "midjourney-prompt-optimizer",
    summary: "优化提示词，生成更高质量的图像。",
    categoryName: "设计",
    tags: [
      { id: "tag_design", name: "设计", type: "scene" },
      { id: "tag_image", name: "图像", type: "type" },
    ],
    difficulty: "intermediate",
    favoriteCount: 1500,
    viewCount: 7100,
    isFeatured: false,
    isHot: true,
  },
  {
    id: "skill_email",
    title: "邮件润色助手",
    slug: "email-polisher",
    summary: "让邮件表达更专业、简洁且高效。",
    categoryName: "办公",
    tags: [
      { id: "tag_mail", name: "邮件", type: "scene" },
      { id: "tag_office_2", name: "办公", type: "type" },
    ],
    difficulty: "beginner",
    favoriteCount: 1300,
    viewCount: 6200,
    isFeatured: false,
    isHot: false,
  },
  {
    id: "skill_video_script",
    title: "短视频脚本创作",
    slug: "short-video-script",
    summary: "围绕选题快速生成短视频脚本与分镜。",
    categoryName: "视频",
    tags: [
      { id: "tag_video", name: "视频", type: "scene" },
      { id: "tag_script", name: "创作", type: "type" },
    ],
    difficulty: "intermediate",
    favoriteCount: 1200,
    viewCount: 6000,
    isFeatured: false,
    isHot: false,
  },
  {
    id: "skill_code_comment",
    title: "代码注释生成",
    slug: "code-comment-generator",
    summary: "自动补充代码注释，帮助理解与维护。",
    categoryName: "编程",
    tags: [
      { id: "tag_code", name: "编程", type: "scene" },
      { id: "tag_dev", name: "开发", type: "type" },
    ],
    difficulty: "intermediate",
    favoriteCount: 1100,
    viewCount: 5400,
    isFeatured: false,
    isHot: false,
  },
  {
    id: "skill_social_calendar",
    title: "社媒文案日历生成",
    slug: "social-calendar-generator",
    summary: "生成一周社媒文案与发布节奏建议。",
    categoryName: "营销",
    tags: [
      { id: "tag_social", name: "社媒", type: "scene" },
      { id: "tag_content", name: "内容", type: "type" },
    ],
    difficulty: "beginner",
    favoriteCount: 987,
    viewCount: 4300,
    isFeatured: false,
    isHot: false,
  },
];

const tutorials: TutorialItem[] = [
  {
    id: "tutorial_prompt_basic",
    title: "零基础学会写 Prompt",
    slug: "prompt-basic",
    summary: "从提示词基础到进阶技巧，写出更聪明的 Prompt。",
    chapterCount: 5,
    durationMinutes: 20,
  },
  {
    id: "tutorial_productivity",
    title: "如何用 AI 提升办公效率",
    slug: "ai-office-productivity",
    summary: "掌握 AI 在文档、表格、PPT 等场景的高效用法。",
    chapterCount: 6,
    durationMinutes: 25,
  },
  {
    id: "tutorial_workflow",
    title: "从 0 到 1 搭建个人 AI 工作流",
    slug: "personal-ai-workflow",
    summary: "学习构建自动化工作流，打造成熟的 AI 助手。",
    chapterCount: 7,
    durationMinutes: 35,
  },
];

export const homepageData: HomepageData = {
  categories,
  featuredSkills,
  latestSkills,
  tutorials,
  stats: {
    skillFavorites: 10000,
    qualityTemplates: 2000,
    monthlyVisits: 50000,
    beginnerTutorials: 30,
  },
};

export function getHomepageMockData(): HomepageData {
  return homepageData;
}
